# version: 20210118
FROM cyclica/chemnix:20210118
MAINTAINER Steve Constable <steve.constable@cyclicarx.com>
RUN apt-get update && apt-get install -y \
    postgresql \
    libpq-dev \
    libxml2-dev \
    libxslt1-dev \
    libmysqlclient-dev
