# version: 20220121
FROM cyclica/chemnix:20220121
MAINTAINER Steve Constable <steve.constable@cyclicarx.com>
RUN apt-get update && apt-get install -y \
    postgresql \
    libpq-dev \
    libxml2-dev \
    libxslt1-dev \
    libcurl4-nss-dev \
    libmysqlclient-dev
