# version: 20220411
FROM cyclica/chemnix:20220411
MAINTAINER Steve Constable <steve.constable@cyclicarx.com>
RUN apt-get update && apt-get install -y \
    postgresql \
    libxml2-dev \
    libxslt1-dev \
    libmysqlclient-dev
